//
//  iOSMobileSDK
//  Copyright Gracenote Inc. 2010. All rights reserved.
//

#import "GNFingerprintResult.h"

@class GNConfig;

/**
 * Container class for all responses generated from operations.
 * A recognition or search operation can generate multiple responses.
 * These can be retrieved by the application for processing. 
 */
@interface GNSearchResult : GNFingerprintResult {
  @private
	NSArray *m_responses;
}

// responses : array of GNSearchResponse objects
// Most queries return just a single "best" response.
// Note that in the case of a nil responses, we
// return an empty array so that user code can
// always iterate over the responses with a
// for each iterator without having to check
// for the null responses case.

/**
 * Collection of responses to the associated operation. 
 */
@property (nonatomic, copy) NSArray *responses;


// bestResponse : alias for [[obj responses] objectAtIndex:0]
// This shortcut returns the "best" response by accessing
// the first element of the responses property. This method
// returns nil if the responses property is nil.

/**
 * Returns the best match generated by the associated operation.
 * Mobile Client operations compute the best match to a recognition or
 * search query; this best match is made available by this method.
 * The best match response also appears in the array of responses returned 
 * by the getResponses() method.
 * @return Best match response generated by the associated operation. When no
 * responses are generated, returns nil.
 */
- (GNSearchResponse*) bestResponse;

@end
